# Generated by Django 5.0.1 on 2024-02-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category Description')),
            ],
        ),
        migrations.CreateModel(
            name='CostInvested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nams', models.CharField(max_length=225, verbose_name='Business Name')),
                ('location', models.CharField(max_length=225, verbose_name='Location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.businesscategory', verbose_name='Business Category')),
                ('cost_invested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_management.costinvested', verbose_name='Cost Invested')),
            ],
        ),
    ]
