# Generated by Django 5.0.1 on 2024-02-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='nams',
            new_name='name',
        ),
    ]
